### PR TITLE
Fix panic in TestMiniController_FailMarshalKey_OnStart

### LINKED ISSUE #249: TestMiniController_FailMarshalKey_OnStart segfaults
https://github.com/dedis/dela/pull/246#issuecomment-1479948341

### PR DESCRIPTION
**Pull request by pierluca**
This is a candidate fix as it's hard to reproduce locally on my Mac, I'll be using the CI to verify.

Fixes #249

### CODE REVIEW

**Comment by pierluca** [comment]
Observations: The fake store implementation didn't respect the API's intentions.
It's unclear if this is the cause of the bug we observe.

**Comment by pierluca** [comment]
Observation: fixing the fake store prevents the panic.

However, the test still fails and it appears the panic was caused by the test going "too far" before failing.

I'm now testing the hypothesis that the failure is due to a file existing (unexpectedly) in the filesystem.

**Comment by pierluca** [comment]
Conclusion: the test failure was due to changes in the Golang crypto library.

The elliptic curve we assumed would be unsupported is now fully supported.

As such, I've modified the `badCurve` implementation to be a genuinely broken, unsupported implementation.

**Review by lourkeur — COMMENTED** [review]
LGTM. I can reproduce the failure locally. Looks like `mino/minogrpc/controller/cert.key` needs to be removed sometimes because tests leave it laying around.

**Review by lourkeur — APPROVED** [review]

File: internal/testing/fake/store.go [hunk 1]
```diff
@@ -130,7 +130,13 @@ func (tx dbTx) GetBucket(name []byte) kv.Bucket {
...
 // GetBucketOrCreate implements kv.WritableTx.
 func (tx dbTx) GetBucketOrCreate(name []byte) (kv.Bucket, error) {
-	return tx.GetBucket(name), tx.err
+	bucket, found := tx.buckets[string(name)]
+	if !found {
+		bucket = NewBucket()
+		tx.buckets[string(name)] = bucket
+	}
+
+	return bucket, tx.err
```
Comment (jbsv) [inline internal/testing/fake/store.go:139]: I wonder if "tx.err" will ever contain an error, as we handle the error case through "found" ? And if it never contains an error, it would be less misleading to return "nil".

File: mino/minogrpc/controller/mod_test.go [hunk 2]
```diff
@@ -418,6 +422,31 @@ func (badReader) Read([]byte) (int, error) {
...
+		N:    big.NewInt(65536),
+	}
+}
+
+func (b badCurve) IsOnCurve(x, y *big.Int) bool {
+	return false
+}
+
+func (b badCurve) Add(x1, y1, x2, y2 *big.Int) (x, y *big.Int) {
+	panic("unsupported")
```
Comment (jbsv) [inline mino/minogrpc/controller/mod_test.go:439]: would being more verbose help here ? Like "bad curve is intentionally unsupported".

**Review by jbsv — COMMENTED** [review]
Besides a couple of questions, LGTM

File: mino/minogrpc/controller/mod_test.go (hunk 2 above)
Comment (pierluca) [reply mino/minogrpc/controller/mod_test.go:439]: In this case it's more of a "not implemented" , because I didn't need to for my test , but point taken 😅
